name: release

on:
  push:
    branches:
      - 'master'

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      -
        uses: salsify/action-detect-and-tag-new-version@v2
        id: version-detect
        with:
          create-tag: false
      - name: Commit report
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git tag -a v${{steps.version-detect.outputs.current-version}} -m "v${{steps.version-detect.outputs.current-version}}"
          git commit -m "Automated release v${{steps.version-detect.outputs.current-version}}"
          git push --follow-tags
